apiVersion: v1
kind: ConfigMap
metadata:
  name: cat-sys-config
  namespace: cat-sys
data:
  APP_NAME: "Cat_Sys"
  URL_PREFIX: "/cat"
  API_GATEWAY_PORT: "9002"
  USER_SERVICE_PORT: "5001"
  MERCHANT_SERVICE_PORT: "5002"
  CAT_SERVICE_PORT: "5003"
  CRM_SERVICE_PORT: "5004"
  FINANCE_SERVICE_PORT: "5005"
  DASHBOARD_SERVICE_PORT: "5006"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRY_MINUTES: "30"
  ENV_MODE: "production"
  # ??????????????
  DOMAIN: "xui6.bbbus.top"
  SERVER_HOST: "67.219.106.150"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "cat_sys"
  MYSQL_USER: "root"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
