apiVersion: v1
kind: Secret
metadata:
  name: cat-sys-secrets
  namespace: cat-sys
type: Opaque
stringData:
  # 注意：密钥不要提交到 git！
  MYSQL_PASSWORD: "change-me-in-production"
  JWT_SECRET: "change-me-in-production"
  REDIS_PASSWORD: ""
